### ISSUE TITLE
Test execution error after updating cssnext

### ISSUE THREAD

**Issue by ahaasler** [ahaasler/hexo-theme-colos#34]
This is the error:

```
/home/ubuntu/workspace/node_modules/postcss-import/index.js:13
var resolvedPromise = new Promise(function(resolvePromise) {
                          ^
ReferenceError: Promise is not defined
  at Object.<anonymous> (/home/ubuntu/workspace/node_modules/postcss-import/index.js:13:27)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/ubuntu/workspace/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/ubuntu/workspace/gulpfile.coffee:6:17)
  at Object.<anonymous> (/home/ubuntu/workspace/gulpfile.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/ubuntu/workspace/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/ubuntu/workspace/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/home/ubuntu/workspace/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/home/ubuntu/workspace/node_modules/gulp/node_modules/liftoff/index.js:193:16)
  at module.exports (/home/ubuntu/workspace/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/home/ubuntu/workspace/node_modules/gulp/node_modules/liftoff/index.js:185:9)
  at /home/ubuntu/workspace/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /home/ubuntu/workspace/node_modules/gulp/node_modules/v8flags/index.js:91:14
  at Object.oncomplete (fs.js:108:15)
```

**Comment by ahaasler** [comment]
Found the issue for another project postcss/postcss-nested#30. Updating node should do it.
